### ISSUE TITLE
What is my board version?

### ISSUE THREAD

**Issue by Teddyz** [atc1441/ZBS_Flasher#30]
Is it as simple as my board is version 029?
The demo-files works on my board, but I guess they are meant for version 033?
![image](https://user-images.githubusercontent.com/14166139/223575568-03e32ad6-140c-4be1-a4c7-6ca52ca61d94.png)

**Comment by atc1441** [comment]
Hey, 
it depends on the display that is connected, the PCB is mostly the same.
If the firmware works for you the display should be the right one

**Comment by Teddyz** [comment]
Thanks!
