### ISSUE TITLE
zbs_flasher.py can only read?

### ISSUE THREAD

**Issue by Smoeller0** [atc1441/ZBS_Flasher#33]
Hello
i just try to flash my first ZBS. The esp32 works the led flashes. 
I think i can read from ZBS chip but can not write? What can the possible error?
i also think the flash is erased. after this the chip uses 7mA at 3,3v and no more update the display.

python3 zbs_flasher.py -p /dev/ttyUSB0 read-infopage infopage reset
Welcome to the ZBS-Flasher Utility
Using port /dev/ttyUSB0
All done!

python3 zbs_flasher.py -p /dev/ttyUSB0 write demo_firmware_4.2_33_V1.9.0.0.bin reset
Welcome to the ZBS-Flasher Utility
Using port /dev/ttyUSB0
Erasing flash... Done.
Error: Writing to flash failed at 0x00000 tried to write 250 bytes: Writing command returned an error

**Comment by atc1441** [comment]
Hey, what is the content of your dumped infopage? 

It could be a wrong wiring so reading is without errors but still wrong content

**Comment by Smoeller0** [comment]
![hex](https://github.com/atc1441/ZBS_Flasher/assets/101890677/a8e02e03-638f-475d-bced-86572f25c41e)
this i read from infopage.
what shuld be in the infopage dump? 

wrong wire perhaps. but when i remove any wire i become an read error. exept the txd rxd. are they used ? when disconect txd rxd read works also

**Comment by atc1441** [comment]
Ok that dump does not look correct, only the first 16bytes should be random but everything else should be 0xFF

Please check the wiring, the rx and tx is not needed for flashing.

Would suspect the power not being correct.
Please try to directly connect that to 3.3V

**Comment by Smoeller0** [comment]
![firmware](https://github.com/atc1441/ZBS_Flasher/assets/101890677/f7f5984c-f6a8-479e-9ba4-531ba955a700)
I get an new chip. i add an extra 100nf cap betwen vcc and ground. 
dump the original firmware. this looks like this. can this be right?
after first flash with same error the display notmore refresh. 

The esp32 sometimes need an reboot after read or try flashing. perhaps the error?
the message is timeout and no led on the esp32.

i use an 3,3v power supply direct on the vcc / ground. without reset schematic. 

so tomorrow i add an logicanalyser to see whats going on there.

**Comment by atc1441** [comment]
The dump looks not too bad, but could be the same as with the infopage and only some bytes swaped.

Maybe try the low speed option via --low

**Comment by Smoeller0** [comment]
I try the --slow but the same problem still alive.
this is try reading. Miso looks like the first block is ok then its dying. 
![read](https://github.com/atc1441/ZBS_Flasher/assets/101890677/709a8f7c-8c00-4f66-8b9d-650448e0c2e3)

writing data only one block then it stops. 
![write2](https://github.com/atc1441/ZBS_Flasher/assets/101890677/85beac7d-0bc5-443f-9b6d-f877cba1d6fa)

i re wire an nes esp32 a new display and have the same problem.

**Comment by atc1441** [comment]
Could you please share a picture of your setup, like an overview and one on the solder job. 
Not meant bad just to find a possible solution :)

**Comment by Smoeller0** [comment]
I found the problem. U where right. The Power was the Problem. My cable vom the power supply broke at the clamp but not complete. broke only nearly. measuring show 3.3v but short out only ~20mA then power broke down. 

Now it work fine. I ll thank you.

**Comment by atc1441** [comment]
Perfect :)
